### ISSUE TITLE
Outdated zoom link

### ISSUE THREAD

**Issue by deepskyblue86** [falcosecurity/.github#13]
**Describe the bug**
Zoom link points to https://sysdig.zoom.us/j/213235330 while it shall point to https://zoom.us/my/cncffalcoproject

**How to reproduce it**

**Expected behaviour**

**Screenshots**

**Environment**

- Falco version:

- System info:

- Cloud provider or hardware configuration:
- OS:

- Kernel:

- Installation method:

**Additional context**

**Comment by leodido** [comment]
This should be fixed now. Thanks for reporting it Angelo!

/close
