### ISSUE TITLE
Update security reporting email 

### ISSUE THREAD

**Issue by krisnova** [falcosecurity/.github#5]
**Describe the bug**

Right now our README points to a Sysdig email account. Can we set up a maintainers only account that everyone has access to?

I think we can use the CNCF mailing list or at least use Falco.org with an MX record and use Gmail.

**How to reproduce it**

**Expected behaviour**

**Screenshots**

**Environment**

- Falco version:

- System info:

- Cloud provider or hardware configuration:
- OS:

- Kernel:

- Installation method:

**Additional context**

**Comment by leodido** [comment]
I vote for falco.org emails.

**Comment by leodido** [comment]
https://github.com/falcosecurity/community/issues/56
