### ISSUE TITLE
Contributing guide link offered by Poiana is outdated

### ISSUE THREAD

**Issue by vjjmiras** [falcosecurity/.github#89]
**Describe the bug**

I have observed [here](https://github.com/falcosecurity/falco-website/pull/664#issuecomment-1204877302) that Poiana is pointing the to contributing guide at the URL 
[https://github.com/falcosecurity/falco-website/blob/master/CONTRIBUTING.md](https://github.com/falcosecurity/falco-website/blob/master/CONTRIBUTING.md) 
instead of 
[https://github.com/falcosecurity/.github/blob/master/CONTRIBUTING.md](https://github.com/falcosecurity/.github/blob/master/CONTRIBUTING.md)

The former one doesn't exist anymore.

**How to reproduce it**

**Expected behaviour**

**Screenshots**

**Environment**

- Falco version:

- System info:

- Cloud provider or hardware configuration:
- OS:

- Kernel:

- Installation method:

**Additional context**

**Comment by leogr** [comment]
Dup of https://github.com/falcosecurity/test-infra/issues/430

**Comment by leogr** [comment]
It should be fixed now! :partying_face: 

/close
