### ISSUE TITLE
admiral0 contributing as Independent

### ISSUE THREAD

**Issue by admiral0** [falcosecurity/.github#93]
**Describe the bug**

I noticed that I am registered with `company: Amazon`. I would like this to be moved to Independent - as my employment with amazon has nothing to do with my contributions to the Falco project.

**How to reproduce it**

**Expected behaviour**

**Screenshots**

**Environment**

- Falco version:

- System info:

- Cloud provider or hardware configuration:
- OS:

- Kernel:

- Installation method:

**Additional context**

**Comment by leogr** [comment]
Hey @admiral0 

Thank you for reporting this. I've made a PR to update your affiliation :point_down: which will be merged soon.
https://github.com/falcosecurity/test-infra/pull/810

**Comment by leogr** [comment]
Fixed by https://github.com/falcosecurity/.github/pull/96/files#diff-acb54fa7b6dff1ebf96647f2231a6d62ffda11ea942fb1bb0d7a8be007e26160L144

/close
